### ISSUE TITLE
Scheduled imports do not always run

### ISSUE THREAD

**Issue by Harinivenk** [vanderbilt-redcap/api-sync-module#15]
Hi Mark , 

I think i was able to see the Filter logic field - in exports also in API_SYNC version v1.11.6   . But in v1.11.7. I am not able to see the filter logic .... 

Does import in API -sync needs to be always started manually .In my project.. the exports seems to happen on the designated time . But the imports needs to be always started from my end 

Best

**Comment by mmcev106** [comment]
- The export filter logic feature was removed because it did not work properly, and would require more time than we currently have available to make it work properly.  I might rename this issue and keep it open to discuss the import scheduling issue.
- Off the top of my head, this might be a good place to start troubleshooting the scheduled import issue:
  - What are the values for the `Daily/Hourly Import Minute` and/or `Daily Import Hour` settings?
  - If you go to the **Cron Jobs** page in **Control Center** and search for `API Sync External Module - Imports`, does it look like that cron is running regularly?
  - Are scheduled imports being skipped on all projects, or just one of them?

**Comment by Harinivenk** [comment]
Thanks Mark ,

I think i can still use the export option .. I have just tweeked my usage
as now i can export different set of variables for 2 different projects

I have my Redcap hosted on AWS server.. I am getting a error when i click
on cron jobs in the control center .. I have attached the same here , I am
going on a medical leave for a  month . Please expect  a delayed response
from my side

I have right now scheduled my import on every day at 01:30 .

**Comment by mmcev106** [comment]
I think attachments might be ignored if you respond directly to github notification emails.  Can you attach the file via gitub.com instead?  See the "view it on github" link in email notifications.

**Comment by Harinivenk** [comment]
Hi Mark , 

I am attaching the error screen shot for your reference . 
![cron-jobs-error](https://user-images.githubusercontent.com/22289151/157161634-99f325de-cd22-4d91-ba6b-2fe14fff0aea.JPG)

**Comment by mmcev106** [comment]
@taylorr4, is the stack trace a bug in REDCap core?  Perhaps permissions related?

**Comment by taylorr4** [comment]
@mmcev106 I'm willing to bet that it's permissions-related, but [i've added a fix to STD and LTS](https://github.com/vanderbilt/REDCap/commit/d820b0ec637ee0a752a48c61687f56b18f79cad0) a minute ago so that this won't happen again.

**Comment by mmcev106** [comment]
Thanks @taylorr4!

**Comment by Harinivenk** [comment]
Thanks a ton Mark and Taylor. this solved my cron jobs issue
