### ISSUE TITLE
Module page requests not providing CSRF token

### ISSUE THREAD

**Issue by lsgs** [vanderbilt-redcap/api-sync-module#22]
Since v1.11.14 and the upgrade to framework version 10 the module test page is no longer working. The ajax calls are not using the regular method that gets the CSRF token included in the POST.

When clicking "Export Queued Records":

![image](https://github.com/vanderbilt-redcap/api-sync-module/assets/7444426/82b3275f-4df2-4a71-9eb6-7306ee422cda)

```
API Sync AJAX Response: <br />
<b>Fatal error</b>:  Uncaught Exception: The 'redcap_csrf_token' parameter is required for all browser initiated POSTs to module pages in this module's framework version.  See the documentation for Framework Version 8 for more information, including how to handle custom API requests. in /site/redcap/redcap_v13.10.6/ExternalModules/classes/ExternalModules.php:7610
Stack trace:
#0 /site/redcap/redcap_v13.10.6/ExternalModules/classes/framework/Framework.php(1043): ExternalModules\ExternalModules::checkCSRFToken()
#1 /site/redcap/redcap_v13.10.6/ExternalModules/index.php(127): ExternalModules\Framework-&gt;checkCSRFToken()
#2 {main}
  thrown in <b>/site/redcap/redcap_v13.10.6/ExternalModules/classes/ExternalModules.php</b> on line <b>7610</b>
```

**Comment by ChemiKyle** [comment]
I can't recreate this. It looks like it was corrected by #23 so I am closing this issue.
@lsgs don't hesitate to re-open if you're still affected.

---

Notably, while setting up a project to test this, I got a CSRF token error while trying to save the module configuration, reloading the page resolved the issue. This problem is likely rooted in the EM Framework rather than this module, but I'm writing it down here to avoid forgetting it.
